apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: critica
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`critica.inceptionpoint.ai`) || Host(`api.critica.inceptionpoint.ai`)
      kind: Rule
      services:
        - name: critica
          port: 80
  tls:
    secretName: critica-prod-tls
