apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base
- externalsecret.yaml
- ingressroute.yaml

images:
- name: critica
  newName: 673066883217.dkr.ecr.us-west-2.amazonaws.com/ipoint-critica-prod
  newTag: 47959cd9dd481e37dc453725887c18d3b2547ba7

commonLabels:
  environment: prod

patches:
- path: patches/replicas.yaml
