apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../base
- externalsecret.yaml
- ingressroute.yaml

images:
- name: critica
  newName: 673066883217.dkr.ecr.us-west-2.amazonaws.com/ipoint-critica-prod
  newTag: 1b542e207f0f51a86acb5414f71c211921721b8e

commonLabels:
  environment: prod

patches:
- path: patches/replicas.yaml
