apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../../base
- externalsecret.yaml
- ingressroute.yaml

images:
- name: critica
  newName: 567274077914.dkr.ecr.us-west-2.amazonaws.com/ipoint-critica-prod
  newTag: 82bd30a3a54ffa8a12680a75dadce8647b122b02

commonLabels:
  environment: staging

patches:
- path: patches/replicas.yaml
